[window]
decorations = "None"
startup_mode = "Windowed"
dimensions = {columns = 150, lines = 30}
position = {x = 250, y = 300}
[font]
normal.family = "JetBrains Mono"
size = 10
[cursor]
style = { shape="Beam" }
[scrolling]
history = 100
